<?php
declare(strict_types=1);

/*
 * @generated by `php artisan http:generate ChunkedUpload` - do not edit.
 * Edit app/Core/Upload/Http/generator.php and regenerate instead.
 */

namespace App\Core\Upload\Http\Controllers;

use App\Core\Upload\Actions\Chunked\AbortChunkedUpload\AbortChunkedUploadAction;
use App\Core\Upload\Actions\Chunked\AbortChunkedUpload\AbortChunkedUploadData;
use App\Core\Upload\Actions\Chunked\AppendChunkedUploadChunk\AppendChunkedUploadChunkAction;
use App\Core\Upload\Actions\Chunked\AppendChunkedUploadChunk\AppendChunkedUploadChunkData;
use App\Core\Upload\Actions\Chunked\ShowChunkedUpload\ShowChunkedUploadAction;
use App\Core\Upload\Actions\Chunked\ShowChunkedUpload\ShowChunkedUploadData;
use App\Core\Upload\Actions\Chunked\StartChunkedUpload\StartChunkedUploadAction;
use App\Core\Upload\Actions\Chunked\StartChunkedUpload\StartChunkedUploadData;
use App\Core\Upload\Http\Resources\ChunkedUploadResource;
use App\Http\Controllers\Controller;
use App\Support\Data\Filling\FillFromAuthenticatedUser;
use App\Support\Data\Filling\FillFromRouteParameter;
use App\Support\OpenApi\SingleResourceResponse;
use Illuminate\Http\Response;
use OpenApi\Attributes as OA;

class ChunkedUploadController extends Controller
{
    #[OA\Post(
        path: '/api/v1/uploads/chunked',
        operationId: 'createChunkedUpload',
        summary: 'Create chunked upload',
        security: [['bearerAuth' => []]],
        requestBody: new OA\RequestBody(
            required: true,
            content: new OA\MediaType(mediaType: 'application/json', schema: new OA\Schema(ref: StartChunkedUploadData::class)),
        ),
        tags: ['uploads'],
        responses: [new SingleResourceResponse(ChunkedUploadResource::class, response: '201', description: 'Chunked Upload created')],
    )]
    public function store(
        StartChunkedUploadAction $action,
        #[FillFromAuthenticatedUser('actorUser')]
        StartChunkedUploadData $data,
    ): ChunkedUploadResource
    {
        return ChunkedUploadResource::loaded($action($data));
    }

    #[OA\Post(
        path: '/api/v1/uploads/chunked/{chunkedUpload}/chunks',
        operationId: 'appendChunkedUploadChunk',
        summary: 'Append chunk',
        security: [['bearerAuth' => []]],
        requestBody: new OA\RequestBody(
            required: true,
            content: new OA\MediaType(mediaType: 'multipart/form-data', schema: new OA\Schema(ref: AppendChunkedUploadChunkData::class)),
        ),
        tags: ['uploads'],
        parameters: [new OA\PathParameter(name: 'chunkedUpload', required: true, schema: new OA\Schema(type: 'string'))],
        responses: [
            new SingleResourceResponse(ChunkedUploadResource::class),
            new OA\Response(response: '424', description: 'Chunked Upload not found'),
        ],
    )]
    public function appendChunk(
        AppendChunkedUploadChunkAction $action,
        #[FillFromAuthenticatedUser('actorUser')]
        #[FillFromRouteParameter('id', 'chunkedUpload')]
        AppendChunkedUploadChunkData $data,
    ): ChunkedUploadResource
    {
        return ChunkedUploadResource::loaded($action($data));
    }

    #[OA\Get(
        path: '/api/v1/uploads/chunked/{chunkedUpload}',
        operationId: 'getChunkedUpload',
        summary: 'Show chunked upload',
        security: [['bearerAuth' => []]],
        tags: ['uploads'],
        parameters: [new OA\PathParameter(name: 'chunkedUpload', required: true, schema: new OA\Schema(type: 'string'))],
        responses: [
            new SingleResourceResponse(ChunkedUploadResource::class),
            new OA\Response(response: '424', description: 'Chunked Upload not found'),
        ],
    )]
    public function show(
        ShowChunkedUploadAction $action,
        #[FillFromAuthenticatedUser('actorUser')]
        #[FillFromRouteParameter('id', 'chunkedUpload')]
        ShowChunkedUploadData $data,
    ): ChunkedUploadResource
    {
        return ChunkedUploadResource::loaded($action($data));
    }

    #[OA\Delete(
        path: '/api/v1/uploads/chunked/{chunkedUpload}',
        operationId: 'deleteChunkedUpload',
        summary: 'Delete chunked upload',
        security: [['bearerAuth' => []]],
        tags: ['uploads'],
        parameters: [new OA\PathParameter(name: 'chunkedUpload', required: true, schema: new OA\Schema(type: 'string'))],
        responses: [
            new OA\Response(response: '204', description: 'Chunked Upload deleted'),
            new OA\Response(response: '424', description: 'Chunked Upload not found'),
        ],
    )]
    public function destroy(
        AbortChunkedUploadAction $action,
        #[FillFromAuthenticatedUser('actorUser')]
        #[FillFromRouteParameter('id', 'chunkedUpload')]
        AbortChunkedUploadData $data,
    ): Response
    {
        $action($data);

        return response()->noContent();
    }
}
