<?php
declare(strict_types=1);

/*
 * @generated by `php artisan http:generate TemporaryUpload` - do not edit.
 * Edit app/Core/Upload/Http/generator.php and regenerate instead.
 */

namespace App\Core\Upload\Http\Controllers;

use App\Core\Upload\Actions\Chunked\CompleteChunkedUpload\CompleteChunkedUploadAction;
use App\Core\Upload\Actions\Chunked\CompleteChunkedUpload\CompleteChunkedUploadData;
use App\Core\Upload\Actions\StoreUpload\StoreUploadAction;
use App\Core\Upload\Actions\StoreUpload\StoreUploadData;
use App\Core\Upload\Http\Resources\TemporaryUploadResource;
use App\Http\Controllers\Controller;
use App\Support\Data\Filling\FillFromAuthenticatedUser;
use App\Support\Data\Filling\FillFromRouteParameter;
use App\Support\OpenApi\SingleResourceResponse;
use OpenApi\Attributes as OA;

class UploadController extends Controller
{
    #[OA\Post(
        path: '/api/v1/uploads',
        operationId: 'createTemporaryUpload',
        summary: 'Create temporary upload',
        security: [['bearerAuth' => []]],
        requestBody: new OA\RequestBody(
            required: true,
            content: new OA\MediaType(mediaType: 'multipart/form-data', schema: new OA\Schema(ref: StoreUploadData::class)),
        ),
        tags: ['uploads'],
        responses: [new SingleResourceResponse(TemporaryUploadResource::class, response: '201', description: 'Temporary Upload created')],
    )]
    public function store(
        StoreUploadAction $action,
        #[FillFromAuthenticatedUser('actorUser')]
        StoreUploadData $data,
    ): TemporaryUploadResource
    {
        return TemporaryUploadResource::loaded($action($data));
    }

    #[OA\Post(
        path: '/api/v1/uploads/chunked/{chunkedUpload}/complete',
        operationId: 'completeTemporaryUploadChunked',
        summary: 'Complete chunked',
        security: [['bearerAuth' => []]],
        tags: ['uploads'],
        parameters: [new OA\PathParameter(name: 'chunkedUpload', required: true, schema: new OA\Schema(type: 'string'))],
        responses: [
            new SingleResourceResponse(TemporaryUploadResource::class),
            new OA\Response(response: '424', description: 'Temporary Upload not found'),
        ],
    )]
    public function completeChunked(
        CompleteChunkedUploadAction $action,
        #[FillFromAuthenticatedUser('actorUser')]
        #[FillFromRouteParameter('id', 'chunkedUpload')]
        CompleteChunkedUploadData $data,
    ): TemporaryUploadResource
    {
        return TemporaryUploadResource::loaded($action($data));
    }
}
