<?php
declare(strict_types=1);

/*
 * @generated by `php artisan http:generate Post` - do not edit.
 * Edit app/Modules/Post/Http/generator.php and regenerate instead.
 */

namespace App\Modules\Post\Http\Controllers;

use App\Authorization\CheckAuthAbility;
use App\Enums\AuthAbilityEnum;
use App\Http\Controllers\Controller;
use App\Modules\Post\Actions\CreatePost\CreatePostAction;
use App\Modules\Post\Actions\CreatePost\CreatePostData;
use App\Modules\Post\Actions\DestroyPost\DestroyPostAction;
use App\Modules\Post\Actions\DestroyPost\DestroyPostData;
use App\Modules\Post\Actions\RestorePost\RestorePostAction;
use App\Modules\Post\Actions\RestorePost\RestorePostData;
use App\Modules\Post\Actions\ShowPost\ShowPostAction;
use App\Modules\Post\Actions\ShowPost\ShowPostData;
use App\Modules\Post\Actions\UpdatePost\UpdatePostAction;
use App\Modules\Post\Actions\UpdatePost\UpdatePostData;
use App\Modules\Post\Enums\PostMediaCollectionEnum;
use App\Modules\Post\Http\Queries\PostIndexQuery;
use App\Modules\Post\Http\Resources\PostResource;
use App\Modules\Post\Models\Post;
use App\Modules\Post\VO\PostIdentifier;
use App\Support\Data\Filling\FillFromAuthenticatedUser;
use App\Support\Data\Filling\FillFromRouteParameter;
use App\Support\OpenApi\PaginatedResourceResponse;
use App\Support\OpenApi\SingleResourceResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Gate;
use OpenApi\Attributes as OA;

class PostController extends Controller
{
    #[OA\Get(
        path: '/api/v1/posts',
        operationId: 'getPosts',
        summary: 'List posts',
        security: [['bearerAuth' => []]],
        tags: ['posts'],
        parameters: [
            new OA\QueryParameter(name: 'page', schema: new OA\Schema(type: 'integer', default: 1, minimum: 1)),
            new OA\QueryParameter(name: 'per_page', schema: new OA\Schema(type: 'integer', default: 15, enum: [15, 25, 50, 100])),
            new OA\QueryParameter(
                name: 'sort',
                description: 'Sort field, prefix with `-` for descending order',
                schema: new OA\Schema(type: 'string', default: 'id', enum: ['id', '-id', 'title', '-title', 'created_at', '-created_at']),
            ),
            new OA\QueryParameter(name: 'filter[title]', description: 'Partial title match', schema: new OA\Schema(type: 'string')),
            new OA\QueryParameter(
                name: 'filter[trashed]',
                description: 'Include soft-deleted posts',
                schema: new OA\Schema(type: 'string', enum: ['with', 'only']),
            ),
            new OA\QueryParameter(
                name: 'filter[search]',
                description: 'Partial match against title and content',
                schema: new OA\Schema(type: 'string'),
            ),
            new OA\QueryParameter(
                name: 'filter[created_at][from]',
                description: 'Unix timestamp in milliseconds',
                schema: new OA\Schema(type: 'integer', format: 'int64'),
            ),
            new OA\QueryParameter(
                name: 'filter[created_at][to]',
                description: 'Unix timestamp in milliseconds',
                schema: new OA\Schema(type: 'integer', format: 'int64'),
            ),
        ],
        responses: [new PaginatedResourceResponse(PostResource::class), new OA\Response(response: '403', description: 'Forbidden')],
    )]
    #[CheckAuthAbility(AuthAbilityEnum::Access, Post::class)]
    public function index(PostIndexQuery $query): AnonymousResourceCollection
    {
        return PostResource::collection($query->paginate());
    }

    #[OA\Get(
        path: '/api/v1/posts/{post}',
        operationId: 'getPost',
        summary: 'Show post',
        security: [['bearerAuth' => []]],
        tags: ['posts'],
        parameters: [new OA\PathParameter(name: 'post', required: true, schema: new OA\Schema(type: 'string'))],
        responses: [
            new SingleResourceResponse(PostResource::class),
            new OA\Response(response: '403', description: 'Forbidden'),
            new OA\Response(response: '424', description: 'Post not found'),
        ],
    )]
    #[CheckAuthAbility(AuthAbilityEnum::Access, Post::class)]
    public function show(
        ShowPostAction $action,
        #[FillFromAuthenticatedUser('actorUser')]
        #[FillFromRouteParameter('id', 'post')]
        ShowPostData $data,
    ): PostResource
    {
        return PostResource::loaded($action($data));
    }

    #[OA\Post(
        path: '/api/v1/posts',
        operationId: 'createPost',
        summary: 'Create post',
        security: [['bearerAuth' => []]],
        requestBody: new OA\RequestBody(
            required: true,
            content: new OA\MediaType(mediaType: 'multipart/form-data', schema: new OA\Schema(ref: CreatePostData::class)),
        ),
        tags: ['posts'],
        responses: [
            new SingleResourceResponse(PostResource::class, response: '201', description: 'Post created'),
            new OA\Response(response: '403', description: 'Forbidden'),
        ],
    )]
    #[CheckAuthAbility(AuthAbilityEnum::Access, Post::class)]
    public function store(
        CreatePostAction $action,
        #[FillFromAuthenticatedUser('authorUser')]
        CreatePostData $data,
    ): PostResource
    {
        return PostResource::loaded($action($data));
    }

    #[OA\Put(
        path: '/api/v1/posts/{post}',
        operationId: 'updatePost',
        summary: 'Update post',
        security: [['bearerAuth' => []]],
        requestBody: new OA\RequestBody(
            required: true,
            content: new OA\MediaType(mediaType: 'multipart/form-data', schema: new OA\Schema(ref: UpdatePostData::class)),
        ),
        tags: ['posts'],
        parameters: [new OA\PathParameter(name: 'post', required: true, schema: new OA\Schema(type: 'string'))],
        responses: [
            new SingleResourceResponse(PostResource::class, description: 'Post updated'),
            new OA\Response(response: '403', description: 'Forbidden'),
            new OA\Response(response: '424', description: 'Post not found'),
        ],
    )]
    #[CheckAuthAbility(AuthAbilityEnum::Access, Post::class)]
    public function update(
        UpdatePostAction $action,
        #[FillFromAuthenticatedUser('actorUser')]
        #[FillFromRouteParameter('id', 'post')]
        UpdatePostData $data,
    ): PostResource
    {
        return PostResource::loaded($action($data));
    }

    #[OA\Delete(
        path: '/api/v1/posts/{post}',
        operationId: 'deletePost',
        summary: 'Delete post',
        security: [['bearerAuth' => []]],
        tags: ['posts'],
        parameters: [new OA\PathParameter(name: 'post', required: true, schema: new OA\Schema(type: 'string'))],
        responses: [
            new OA\Response(response: '204', description: 'Post deleted'),
            new OA\Response(response: '403', description: 'Forbidden'),
            new OA\Response(response: '424', description: 'Post not found'),
        ],
    )]
    #[CheckAuthAbility(AuthAbilityEnum::Access, Post::class)]
    public function destroy(
        DestroyPostAction $action,
        #[FillFromAuthenticatedUser('actorUser')]
        #[FillFromRouteParameter('id', 'post')]
        DestroyPostData $data,
    ): Response
    {
        $action($data);

        return response()->noContent();
    }

    #[OA\Post(
        path: '/api/v1/posts/{post}/restore',
        operationId: 'restorePost',
        summary: 'Restore post',
        security: [['bearerAuth' => []]],
        tags: ['posts'],
        parameters: [new OA\PathParameter(name: 'post', required: true, schema: new OA\Schema(type: 'string'))],
        responses: [
            new SingleResourceResponse(PostResource::class),
            new OA\Response(response: '403', description: 'Forbidden'),
            new OA\Response(response: '424', description: 'Post not found'),
        ],
    )]
    #[CheckAuthAbility(AuthAbilityEnum::Access, Post::class)]
    public function restore(
        RestorePostAction $action,
        #[FillFromAuthenticatedUser('actorUser')]
        #[FillFromRouteParameter('id', 'post')]
        RestorePostData $data,
    ): PostResource
    {
        return PostResource::loaded($action($data));
    }

    #[OA\Delete(
        path: '/api/v1/posts/{post}/cover',
        operationId: 'removePostCover',
        summary: 'Remove cover',
        security: [['bearerAuth' => []]],
        tags: ['posts'],
        parameters: [new OA\PathParameter(name: 'post', required: true, schema: new OA\Schema(type: 'string'))],
        responses: [new OA\Response(response: '204', description: 'Post cover removed')],
    )]
    #[CheckAuthAbility(AuthAbilityEnum::Access, Post::class)]
    public function removeCover(Request $request): Response
    {
        $id = PostIdentifier::fromRequestParameter($request, 'post');
        $model = Post::query()->findOrFail($id);
        Gate::forUser($request->user())->authorize('update', $model);
        $model->clearMediaCollection(PostMediaCollectionEnum::Cover->value);
        return response()->noContent();
    }
}
