<?php
declare(strict_types=1);

/*
 * @generated by `php artisan http:generate Post` - do not edit.
 * Edit app/Modules/Post/Http/generator.php and regenerate instead.
 */

namespace App\Modules\Post\Http\Controllers;

use App\Authorization\CheckAuthAbility;
use App\Enums\AuthAbilityEnum;
use App\Http\Controllers\Controller;
use App\Modules\Post\Actions\Files\AttachFile\AttachFileAction;
use App\Modules\Post\Actions\Files\AttachFile\AttachFileData;
use App\Modules\Post\Actions\Files\DetachFile\DetachFileAction;
use App\Modules\Post\Actions\Files\DetachFile\DetachFileData;
use App\Modules\Post\Actions\Files\DownloadFile\DownloadFileAction;
use App\Modules\Post\Actions\Files\DownloadFile\DownloadFileData;
use App\Modules\Post\Actions\Files\ListFiles\ListFilesAction;
use App\Modules\Post\Actions\Files\ListFiles\ListFilesData;
use App\Modules\Post\Actions\Files\RenameFile\RenameFileAction;
use App\Modules\Post\Actions\Files\RenameFile\RenameFileData;
use App\Modules\Post\Domain\VO\PostFileIdentifier;
use App\Modules\Post\Domain\VO\PostIdentifier;
use App\Modules\Post\Http\Resources\PostFileResource;
use App\Modules\Post\Models\Post;
use App\Support\Data\Filling\FillFromAuthenticatedUser;
use App\Support\Data\Filling\FillFromRouteParameter;
use App\Support\OpenApi\ResourceCollectionResponse;
use App\Support\OpenApi\SingleResourceResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;
use Illuminate\Http\Response;
use OpenApi\Attributes as OA;
use Symfony\Component\HttpFoundation\StreamedResponse;

class PostFileController extends Controller
{
    #[OA\Get(
        path: '/api/v1/posts/{post}/files',
        operationId: 'listPostFiles',
        summary: 'List files',
        security: [['bearerAuth' => []]],
        tags: ['post-files'],
        parameters: [new OA\PathParameter(name: 'post', required: true, schema: new OA\Schema(type: 'integer'))],
        responses: [
            new ResourceCollectionResponse(PostFileResource::class),
            new OA\Response(response: '403', description: 'Forbidden'),
            new OA\Response(response: '424', description: 'Post not found'),
        ],
    )]
    #[CheckAuthAbility(AuthAbilityEnum::Access, Post::class)]
    public function listFiles(
        ListFilesAction $action,
        #[FillFromRouteParameter('id', 'post')]
        ListFilesData $data,
    ): AnonymousResourceCollection
    {
        return PostFileResource::collection($action($data));
    }

    #[OA\Post(
        path: '/api/v1/posts/{post}/files',
        operationId: 'attachPostFile',
        summary: 'Attach file',
        security: [['bearerAuth' => []]],
        requestBody: new OA\RequestBody(
            required: true,
            content: new OA\MediaType(mediaType: 'application/json', schema: new OA\Schema(ref: AttachFileData::class)),
        ),
        tags: ['post-files'],
        parameters: [new OA\PathParameter(name: 'post', required: true, schema: new OA\Schema(type: 'integer'))],
        responses: [
            new SingleResourceResponse(PostFileResource::class, response: '201', description: 'File attached'),
            new OA\Response(response: '403', description: 'Forbidden'),
            new OA\Response(response: '424', description: 'Post not found'),
        ],
    )]
    #[CheckAuthAbility(AuthAbilityEnum::Access, Post::class)]
    public function attachFile(
        AttachFileAction $action,
        #[FillFromAuthenticatedUser('actorUser')]
        #[FillFromRouteParameter('id', 'post')]
        AttachFileData $data,
    ): PostFileResource
    {
        return PostFileResource::loaded($action($data));
    }

    #[OA\Patch(
        path: '/api/v1/posts/{post}/files/{file}',
        operationId: 'renamePostFile',
        summary: 'Rename file',
        security: [['bearerAuth' => []]],
        requestBody: new OA\RequestBody(
            required: true,
            content: new OA\MediaType(mediaType: 'application/json', schema: new OA\Schema(ref: RenameFileData::class)),
        ),
        tags: ['post-files'],
        parameters: [
            new OA\PathParameter(name: 'post', required: true, schema: new OA\Schema(type: 'integer')),
            new OA\PathParameter(name: 'file', required: true, schema: new OA\Schema(type: 'string')),
        ],
        responses: [
            new SingleResourceResponse(PostFileResource::class),
            new OA\Response(response: '403', description: 'Forbidden'),
            new OA\Response(response: '424', description: 'Post not found'),
        ],
    )]
    #[CheckAuthAbility(AuthAbilityEnum::Access, Post::class)]
    public function renameFile(
        RenameFileAction $action,
        #[FillFromAuthenticatedUser('actorUser')]
        #[FillFromRouteParameter('id', 'post')]
        #[FillFromRouteParameter('fileId', 'file')]
        RenameFileData $data,
    ): PostFileResource
    {
        return PostFileResource::loaded($action($data));
    }

    #[OA\Delete(
        path: '/api/v1/posts/{post}/files/{file}',
        operationId: 'detachPostFile',
        summary: 'Detach file',
        security: [['bearerAuth' => []]],
        tags: ['post-files'],
        parameters: [
            new OA\PathParameter(name: 'post', required: true, schema: new OA\Schema(type: 'integer')),
            new OA\PathParameter(name: 'file', required: true, schema: new OA\Schema(type: 'string')),
        ],
        responses: [
            new OA\Response(response: '204', description: 'Successful operation'),
            new OA\Response(response: '403', description: 'Forbidden'),
            new OA\Response(response: '424', description: 'Post not found'),
        ],
    )]
    #[CheckAuthAbility(AuthAbilityEnum::Access, Post::class)]
    public function detachFile(
        DetachFileAction $action,
        #[FillFromAuthenticatedUser('actorUser')]
        #[FillFromRouteParameter('id', 'post')]
        #[FillFromRouteParameter('fileId', 'file')]
        DetachFileData $data,
    ): Response
    {
        $action($data);

        return response()->noContent();
    }

    #[OA\Get(
        path: '/api/v1/posts/{post}/files/{file}/download',
        operationId: 'downloadPostFile',
        summary: 'Download file',
        security: [['bearerAuth' => []]],
        tags: ['post-files'],
        parameters: [
            new OA\PathParameter(name: 'post', required: true, schema: new OA\Schema(type: 'string')),
            new OA\PathParameter(name: 'file', required: true, schema: new OA\Schema(type: 'string')),
        ],
        responses: [
            new OA\Response(response: '200', description: 'File contents'),
            new OA\Response(response: '403', description: 'Forbidden'),
            new OA\Response(response: '424', description: 'Post not found'),
        ],
    )]
    #[CheckAuthAbility(AuthAbilityEnum::Access, Post::class)]
    public function downloadFile(Request $request, DownloadFileAction $action): StreamedResponse
    {
        $post = PostIdentifier::fromRequestParameter($request, 'post');
        $file = PostFileIdentifier::fromRequestParameter($request, 'file');
        $media = $action(DownloadFileData::from(['id' => $post, 'fileId' => $file]));
        return $media->toResponse($request);
    }
}
